// TYPESCRIPT IS COMPILING THE tsc FILE TO js FILE WHICH RUNS IN BROWSER USING tsc app.tsc
// WHICH GENERATES app.js
console.log("STARTING TYPESCRIPT, IT'S FUN");
// TYPESCRIPT CHECKS THE COMPILE TIME ERROR
// IF ITS STRING TYPE AND WE GIVE NUMBER IT WILL GIVE NUMBER
// ALSO WE CAN'T CHANGE THE TYPE LATER AS WELL
var movieName = 'The Hero';
// IF METHOD IS NOT AVAILABLE THEN ALSO IT WILL GIVE ERROR
movieName.toUpperCase();
